package plasticmod.plastic;
import cpw.mods.fml.common.ModMetadata;

public class PlasticModData
{
	private static final String BR = System.getProperty("line.separator");
	public static void load(ModMetadata meta)
	{
		meta.modId = PlasticCore.modid;
		meta.name ="plasticmod";
		meta.description ="このMODはプラスチックやその他少量の便利アイテムを追加するMODです。"+ BR +"一部テクスチャ制作:hyuga(友人),skisiksanさん,gintora1125さん 使用させていただいた音源サイトさん:On-Jin ～音人～ URL:http://on-jin.com/";
		meta.version =PlasticCore.version ;
		meta.credits = "制作:noriokun4649 一部テクスチャ制作:下記参照 音源サイトさん:下記参照";
		meta.logoFile = "logo.png";
		meta.url = "http://forum.minecraftuser.jp/viewtopic.php?f=13&t=26845";
		meta.updateUrl = "https://dl.dropboxusercontent.com/s/4otqd1x8cqz9wlt/Plasticmod_update.json";
		meta.autogenerated = false;
	}
}
