package plasticmod.plastic.villager;

import java.util.Random;

import cpw.mods.fml.common.registry.VillagerRegistry.IVillageTradeHandler;
import net.minecraft.entity.passive.EntityVillager;
import net.minecraft.item.ItemStack;
import net.minecraft.village.MerchantRecipe;
import net.minecraft.village.MerchantRecipeList;
import plasticmod.plastic.PlasticCore;
import plasticmod.plastic.config.PlasticConfig;
/*
 * 村人との取引を操作するクラスです
 */
public class PlasticVillage implements IVillageTradeHandler {

	@Override
	public void manipulateTradesForVillager(EntityVillager villager,
			MerchantRecipeList recipeList, Random random) {
		/*
		 * 今回新しく作成した職業用の取引内容を登録します
		 * 既存の職業に取引を追加したりもできます
		 */
		if(villager.getProfession() == PlasticConfig.PlasticVillagerID) {
			/*
			 * エメラルド１個を村人に売って金のリンゴを１個買う取引を登録
			 */
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockaqua)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockblack)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocknavy)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkgreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockgreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockteal)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkcyan)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdeepskyblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkturquoise)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumspringgreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockspringgreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklime)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockaqua)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockcyan)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmidnightblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdodgerblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightseagreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockforestgreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockseagreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkslategray)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklimegreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumseagreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockturquoise)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockroyalblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksteelblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkslateblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumturquoise)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockindigo)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkolivegreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockcadetblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockcornflowerblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumaquamarine)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdimgray)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockslateblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockolivedrab)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockslategray)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightslategray)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumslateblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklawngreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockchartreuse)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockaquamarine)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmaroon)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpurple)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockolive)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockgray)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockskyblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightskyblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockblueviolet)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkred)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkmagenta)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksaddlebrown)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkseagreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightgreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumpurple)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkviolet)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpalegreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkorchid)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockyellowgreen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksienna)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockbrown)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkgray)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockgreenyellow)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpaleturquoise)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightsteelblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpowderblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockfirebrick)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkgoldenrod)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumorchid)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockrosybrown)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkkhaki)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksilver)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumvioletred)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockindianred)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockperu)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockchocolate)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocktan)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightgrey)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockthistle)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockorchid)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockgoldenrod)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpalevioletred)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockcrimson)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockgainsboro)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockplum)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockburlywood)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightcyan)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklavender)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarksalmon)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockviolet)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpalegoldenrod)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightcoral)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockkhaki)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockaliceblue)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockhoneydew)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockazure)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksandybrown)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockwheat)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockbeige)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockwhitesmoke)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmintcream)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockghostwhite)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksalmon)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockantiquewhite)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklinen)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightgoldenrodyellow)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockoldlace)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockred)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockfuchsia)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmagenta)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdeeppink)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockorangered)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocktomato)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockhotpink)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockcoral)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkorange)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightsalmon)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockorange)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightpink)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpink)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockgold)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpeachpuff)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocknavajowhite)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmoccasin)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockbisque)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmistyrose)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockblanchedalmond)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpapayawhip)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklavenderblush)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockseashell)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockcornsilk)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklemonchiffon)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockfloralwhite)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksnow)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockyellow)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightyellow)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockivory)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockwhite)));

			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockblackCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocknavyCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkgreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockgreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocktealCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkcyanCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdeepskyblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkturquoiseCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumspringgreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockspringgreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklimeCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockaquaCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockcyanCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmidnightblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdodgerblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightseagreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockforestgreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockseagreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkslategrayCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklimegreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumseagreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockturquoiseCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockroyalblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksteelblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkslateblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumturquoiseCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockindigoCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkolivegreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockcadetblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockcornflowerblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumaquamarineCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdimgrayCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockslateblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockolivedrabCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockslategrayCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightslategrayCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumslateblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklawngreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockchartreuseCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockaquamarineCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmaroonCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpurpleCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockoliveCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockgrayCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockskyblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightskyblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockbluevioletCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkredCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkmagentaCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksaddlebrownCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkseagreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightgreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumpurpleCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkvioletCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpalegreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkorchidCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockyellowgreenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksiennaCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockbrownCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkgrayCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockgreenyellowCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpaleturquoiseCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightsteelblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpowderblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockfirebrickCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkgoldenrodCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumorchidCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockrosybrownCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkkhakiCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksilverCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmediumvioletredCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockindianredCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockperuCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockchocolateCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocktanCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightgreyCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockthistleCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockorchidCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockgoldenrodCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpalevioletredCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockcrimsonCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockgainsboroCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockplumCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockburlywoodCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightcyanCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklavenderCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarksalmonCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockvioletCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpalegoldenrodCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightcoralCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockkhakiCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockaliceblueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockhoneydewCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockazureCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksandybrownCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockwheatCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockbeigeCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockwhitesmokeCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmintcreamCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockghostwhiteCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksalmonCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockantiquewhiteCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklinenCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightgoldenrodyellowCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockoldlaceCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockredCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockfuchsiaCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmagentaCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdeeppinkCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockorangeredCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocktomatoCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockhotpinkCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockcoralCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockdarkorangeCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightsalmonCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockorangeCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightpinkCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpinkCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockgoldCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpeachpuffCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocknavajowhiteCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmoccasinCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockbisqueCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockmistyroseCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockblanchedalmondCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockpapayawhipCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklavenderblushCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockseashellCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockcornsilkCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklemonchiffonCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockfloralwhiteCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocksnowCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockyellowCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblocklightyellowCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockivoryCarpet,6,0)));
			recipeList.add(new MerchantRecipe( new ItemStack(PlasticCore.plasticblock, 1, 0),new ItemStack ( PlasticCore.plasticblockwhiteCarpet,6,0)));
		}
	}
}